export const portfolio = {
  identity: {
    name: "Ethan Urbanky",
    tagline: "Data Science & Software Engineering · 3× CI Financial Intern · Co-Founder @ CONQ",
    location: "London, Ontario, Canada",
    email: "ethan.urbanky@gmail.com",
    phone: "+1 (647) 710-2061",
    links: {
      website: "https://ethanurbanky.dev",
      linkedin: "https://linkedin.com/in/ethan-urbanky",
      github: "https://github.com/ethanurbanky2005",
      primary_repo: "https://github.com/ethanurbanky2005/UPickv0",
    },
    languages: ["English (Native)", "French (Native)"],
  },
  creative: {
    coreTheme: "Dream OS × Timeline Galaxy",
    defaultMode: "dark" as const,
    skins: ["studio", "stage", "archive"] as const,
  },

  aboutNodes: [
    { id: "origin", symbol: "↺", meaning: "curiosity loop" },
    { id: "craft", symbol: "◯", meaning: "soft precision" },
    { id: "values", symbol: "✦", meaning: "clarity through light" },
  ],
  resume: {
    education: [
      {
        program: "BSc (Hons) Specialization in Data Science",
        institution: "University of Western Ontario",
        location: "London, Ontario",
        gradYear: 2027,
        highlights: ["BUIS 2295F/G — Business for Science (Ivey Case Method)"],
      },
      {
        program: "High School Diploma / International Baccalaureate",
        institution: "Upper Canada College",
        location: "Toronto, Ontario",
        gradYear: 2023,
        highlights: ["Co-Founded Quantum Computing Club", "Varsity Rugby Athlete", "JV Football"],
      },
    ],
    certifications: [
      {
        name: "Exploring SAP Business Technology Platform",
        issuer: "SAP Learning",
        date: "May 2026",
        level: "Beginner",
      },
      {
        name: "Discovering SAP Activate — Implementation Tools and Methodology",
        issuer: "SAP Learning",
        date: "May 2026",
        level: "Intermediate",
      },
    ],
    experience: [
      {
        role: "Application Architecture Intern",
        company: "CI Financial",
        period: "May 2025 — Aug 2025",
        location: "Toronto, ON",
        bullets: [
          "Led Snowflake cloud platform integration across $103B wealth management division",
          "Validated 2M+ client records across 4 transformation stages with 99.9% accuracy",
          "Automated Jira sprint workflows cutting 10+ hours of manual overhead per sprint",
          "Mapped As-Is Sybase/SQR pipelines to future-state cloud architecture across 50+ data pipelines",
        ],
        stack: ["Python", "Snowflake", "SQL", "Bash", "Jira"],
      },
      {
        role: "Full-Stack Developer Intern",
        company: "CI Financial",
        period: "May 2024 — Aug 2024",
        location: "Toronto, ON",
        bullets: [
          "Built advisory platform serving 900+ financial advisors managing $46B in assets",
          "Integrated 5+ financial APIs into real-time dashboards across 6 Agile sprints",
          "Facilitated cross-functional sprint reviews between business and technical teams",
          "Produced audience-tailored presentations for non-technical stakeholder groups",
        ],
        stack: ["Django", "React.js", "Python", "Tailwind CSS", "TypeScript"],
      },
      {
        role: "Software Developer Intern",
        company: "CI Financial",
        period: "Jun 2023 — Aug 2023",
        location: "Toronto, ON",
        bullets: [
          "Delivered end-to-end internal web application in 8 weeks from requirements to deployment",
          "Conducted structured requirements analysis across 3 stakeholder groups",
          "Contributed to 10+ Agile ceremonies ensuring on-time delivery",
        ],
        stack: ["Django", "Python", "PostgreSQL", "JavaScript", "HTML5"],
      },
    ],
    skills: {
      languages: ["Python", "TypeScript", "JavaScript", "Java", "SQL", "Bash"],
      frameworks: ["React.js", "Next.js", "Django", "Flask", "Tailwind CSS"],
      data: ["pandas", "scikit-learn", "matplotlib", "seaborn", "NumPy", "Snowflake"],
      cloud: ["SAP S/4HANA", "SAP BTP", "Supabase", "Vercel"],
      practices: ["Agile (Scrum)", "As-Is/To-Be Process Mapping", "ETL Pipelines", "REST APIs", "CI/CD"],
      soft: ["Bilingual French/English", "Stakeholder Alignment", "Quantitative Analysis"],
    },
  },
  projects: [
    {
      id: "conq",
      title: "CONQ",
      role: "Co-Founder & ML/AI Technical Lead",
      description: "AI-powered smart glasses for concussion recovery monitoring in contact sports. Built a multi-modal ML pipeline processing 5 concurrent biometric sensor streams — accelerometer, gyroscope, ECG, SpO2, and skin temperature — for real-time recovery classification. Targeting the OHL at $12K–$20K per team-season inside the $6.58B global concussion market. Competed in UWO Presidents Challenge 2026.",
      tech: ["Python", "Machine Learning", "scikit-learn", "pandas", "React.js", "Next.js"],
      icon: "CONQ",
      github: null,
      demo: "https://conq.ca",
      mass: 1.0,
    },
    {
      id: "upick",
      title: "UPick",
      role: "Founder & Developer",
      description: "Machine learning platform for college football parlay picking. Full-stack application with Python backend and React frontend, implementing advanced ML models with feature engineering and probability calibration against live odds data.",
      tech: ["Python", "Flask", "React.js", "Machine Learning", "OddsAPI", "Sportradar"],
      icon: "UPick",
      github: "https://github.com/ethanurbanky2005/UPickv0.git",
      demo: null,
      mass: 0.9,
    },
    {
      id: "financetrack",
      title: "FinanceTrack",
      role: "Full-Stack Developer",
      description: "Comprehensive financial management application with dashboard analytics, transaction tracking, subscription management, and tax liability monitoring. Features secure authentication, data visualization, and real-time budget tracking.",
      tech: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS", "shadcn/ui", "Recharts"],
      icon: "FinanceTrack",
      github: "https://github.com/ethanurbanky2005/FinanceTrack.git",
      demo: "https://financetrack-personal.vercel.app",
      mass: 0.8,
    },
  ],
};
